### ISSUE TITLE
Remove old functions and update docs

### ISSUE THREAD

**Issue by caseymm** [datadesk/nifc-wildfires#5]

**Comment by palewire** [comment]
Looking at this quickly, I think the work will entail:
- [x] Removing the old shapefile based functions for incidents and parameters
- [x] Removing the shapefile dependencies like fiona and geojson
- [x] Renaming the new json functions with simpler names, like perimeters and incidents
- [x] Updating the documentation and tests to only use the new functions

And with the GeoMAC site being deprecated with links off to NIFC as the new data provider, I wonder if we should even consider renaming this package from `geomac-wildfires` to `nifc-wildfires`.

**Comment by palewire** [comment]
Reference material on the GeoMAC deprecation can be found [here](https://geomac.usgs.gov/GeoMACTransition.shtml)
